home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name="index"),
    path('solid', views.setSolid, name="solid"),
    path('cycle', views.setCycle, name="cycle"),
    path('breathing', views.setBreathing, name="breathing"),
    path('off', views.setOff, name="off")
]

webapp_g102/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

home/forms.py
from django import forms

class SolidColorPicker(forms.Form):
    # Color in RGB
    color = forms.CharField(label='Color (in RRGGBB)', max_length=6)

home/views.py
from django.shortcuts import render, redirect
from .g203_led import send_mouse_config

# Create your views here.
def index(request):
    return render(request, 'index.html')

# Solid mode arguments:
# 1. Color (RRGGBB)
def setSolid(request):
    color = request.POST['color-value'][1:]
    send_mouse_config('Solid', [color])

    arguments = {
        'colorValue': color,
        'type': "solid"
    }

    return render(request, 'index.html', arguments)

# Cycle mode arguments:
# 1. Brightness (0-100, default 100)
# 2. Cycle rate (100ms - 60000ms, default 10000ms)
def setCycle(request):
    brightness = request.POST['brightness']
    cycle_rate = request.POST['cycle-rate']
    send_mouse_config('Cycle', [cycle_rate, brightness])

    arguments = {
        'brightness': brightness,
        'cycle_rate': cycle_rate,
        'type': "cycle"
    }

    return render(request, 'index.html', arguments)

# Breathing mode arguments:
# 1. Color (RRGGBB)
# 2. Brightness (0% - 100%, default 100)
# 3. Cycle rate (100ms - 60000ms, default 10000ms)
def setBreathing(request):
    color = request.POST['color-value'][1:]
    brightness = request.POST['brightness']
    cycle_rate = request.POST['cycle-rate']
    send_mouse_config('Breathing', [color, cycle_rate, brightness])

    arguments = {
        'colorValue': color,
        'brightness': brightness,
        'cycle_rate': cycle_rate,
        'type': "breathing"
    }

    return render(request, 'index.html', arguments)

def setOff(request):
    send_mouse_config('Solid', ["000000"])

    arguments = {
        'type': "off"
    }

    return render(request, 'index.html', arguments)

home/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello World!</title>
</head>
<body>
    <h1>M-Config</h1>
    {% if type %}
        <p>Your mouses LED is successfully applied with:</p>
        <p>Type: {{type}}</p>
        {% if type != "off" %}
            {% if type != "cycle" %}
                <p>Color (HEX): #{{colorValue}}</p>
            {% endif %}
            {% if type != "solid" %}
                <p>Brightness: {{brightness}}</p>
                <p>Cycle rate: {{cycle_rate}} ms</p>
            {% endif %}
        {% endif %}
    {% endif %}

    <div class="solid">
        <h2>Apply Solid Color</h2>
        <form method="POST" action="/solid">
            {% csrf_token %}
            <label>Color</label>
            <input type="color" value="#{{colorValue}}" name="color-value">
            <input type="submit" value="Submit" name="submit-btn">
        </form>
    </div>
    <div class="cycle">
        <h2>Apply Cycle Color</h2>
        <form method="POST" action="/cycle">
            {% csrf_token %}
            <label>Brightness</label>
            <input type="number" min="0" max="100" value="100" name="brightness">
            <label>Cycle Rate (ms)</label>
            <input type="number" min="100" max="60000" value="10000" name="cycle-rate">
            <input type="submit" value="Submit" name="submit-btn">
        </form>
    </div>
    <div class="breathing">
        <h2>Apply Breathing Color</h2>
        <form method="POST" action="{% url 'home:breathing' %}">
            {% csrf_token %}
            <label>Color</label>
            <input type="color" value="#{{colorValue}}" name="color-value">
            <label>Brightness</label>
            <input type="number" min="0" max="100" value="100" name="brightness">
            <label>Cycle Rate (ms)</label>
            <input type="number" min="100" max="60000" value="10000" name="cycle-rate">
            <input type="submit" value="Submit" name="submit-btn">
        </form>
    </div>
    <div class="off">
        <h2>Apply Breathing Color</h2>
        <a href="{% url 'home:off' %}">
            <button>Off</button>
        </a>
    </div>
</body>
</html>

home/templates/solid.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Styling CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>Hello World!</title>
</head>
<body>
    <h1>Hai</h1>
    <p>Solid Color yang kamu minta adalah: #{{ colorValue }}</p>
    <div class="div-color" style="background-color: #{{ colorValue }};">hai</div>
</body>
</html>